# Generated by Django 4.1.7 on 2023-05-25 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
